steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudruntest-demo/cloud-runtest:$COMMIT_SHA', '.']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudruntest-demo/cloud-runtest:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'cloud-test'
    - '--image'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudruntest-demo/cloud-runtest:$COMMIT_SHA'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '100'
    - '--allow-unauthenticated'
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudruntest-demo/cloud-runtest'
